models:
  - name: silver_xetra
    description: "Silver Layer Table for Xetra Data"
    meta:
      dagster:
        group: silver
    data_tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          arguments:
            min_value: 1
    columns:
      - name: trading_day
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
