version: 2

sources:
  - name: covid19
    config:
      plugin: delta
    tables:
      - name: germany
        meta:
          delta_table_path: "/Users/moritz/Documents/local-modern-data-stack/data/bronze/germany"
          dagster:
            asset_key: ["bronze", "covid19_data_rki"]
        columns:
          - name: "cases"
            data_tests:
              - not_null
