version: 2

sources:
  - name: covid19
    config:
      plugin: delta
    tables:
      - name: germany
        meta:
          delta_table_path: "dagster_home/data/bronze/germany"
          dagster:
            asset_key: ["bronze", "covid19_data_rki"]
        columns:
          - name: "cases"
            tests:
              - not_null
