models:
  - name: gold_covid
    description: "unified COVID data"
    meta:
      dagster:
        group: gold
    data_tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 1
    columns:
      - name: meta_lastupdate
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
